from django.contrib.auth.models import User
from rest_framework.test import APITestCase, APIClient
from rest_framework import status
from django.urls import reverse
from .models import Post


class RegisterViewSetTest(APITestCase):
    def test_user_registration(self):
        url = reverse('register')  # generated by DefaultRouter for RegisterViewSet
        data = {
            'username': 'testuser',
            'email': 'test@example.com',
            'password': 'testpassword123'
        }
        response = self.client.post(url, data, format='json')
        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        self.assertTrue(User.objects.filter(username='testuser').exists())


class PostViewSetTest(APITestCase):
    def setUp(self):
        self.user = User.objects.create_user(username='john', password='pass1234')
        self.client = APIClient()
        self.client.force_authenticate(user=self.user)

    def test_create_post(self):
        url = reverse('post-list')  # generated by DefaultRouter for PostViewSet
        data = {'title': 'Test Post', 'content': 'This is a test.'}
        response = self.client.post(url, data, format='json')
        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(Post.objects.count(), 1)
        self.assertEqual(Post.objects.first().title, 'Test Post')

    def test_get_posts(self):
        Post.objects.create(title='Sample', content='Hello world')
        url = reverse('post-list')
        response = self.client.get(url, format='json')
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertGreaterEqual(len(response.data), 1)
